version: '3'
services:
  mongo:
    container_name: 'mongo-container'
    image: mongo:4
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
  api:
    container_name: api-container
    restart: always
    build: .
    image: solid-mango
    command: yarn debug
    volumes:
      - ./dist:/usr/src/solid-mango/dist
      - ./package.json:/usr/src/solid-mango/package.json
    ports:
      - '5050:5050'
      - '9222:9222'
    links:
      - mongo